### ISSUE TITLE
Having Trouble with the Source code

### ISSUE THREAD

**Issue by davisaces** [sy2002/TeleBall#1]
Hello, My name is Christopher Davis and I am a Bachelors student using your teleball project for my capstone.  I have came across some issues with the source code. We have included the #include<LedControl.h>, #include<nRF24L01.h>, and the #include<RF24.h> from the websites given in the code. When we try to compile the code we get an error "Ledcontrol.h:30:error:'byte'does not name a type.  Can you please contact me and let me know what I'm doing wrong? Thank you very much

Christopher J. Davis

**Comment by sy2002** [comment]
Hi Christopher,
if the "LED control" library and the "NRF24L01+ radio driver class" are installed correctly, then there should be no need to change anything in the code, it should just compile.

So my first idea would be, that you might not have installed them correctly. Please have a look at this tutorial video I made a while ago, that explains, how to install them. Go to minute 1:30 and watch from there on:

https://www.youtube.com/watch?v=OP6eKLpfZnA

(Attention: The project shown in the tutorial video is a predecessor to TeleBall, so the code is not compatible as it is another project. But it shows the basic principle of how to install the libraries correctly, so that TeleBall's code can make use of it.)

A second idea might be, that in the meantime, i.e. since I wrote TeleBall and today, the libraries might have become incompatible, e.g. because they changed their APIs or so. In that case: Instead of downloading the newest version of the libraries from the web locations mentioned in the code, please use the versions that I supplied together with the TeleBall release bundle on GitHub:

https://github.com/sy2002/TeleBall/archive/V1.2.zip

If you unzip it, you'll find a folder named "src" and there is another ZIP called "libraries.zip". These are the original library version that I used to build TeleBall. You might want to install them as shown in the video above - instead of using the most recent versions from the web.

Best regards 
  sy2002

**Comment by davisaces** [comment]
Sy2002,
Thak you! We put the original libraries as u suggested. You are the man.

God bless
Chris

**Comment by sy2002** [comment]
Hi Chris,
great to hear that this solved your problem! :-)
I am curious: Are you guys building the whole TeleBall device, including 3D printing, custom PCB, etc.?
Best regards
sy2002

**Comment by davisaces** [comment]
No sir.  It was rather pricey so we decided to put it on the bread board.
We couldn't find a 3d printing company around to do so in the matter of
time we had and the custom PCB boards cost too much. I wish we could have
done it, but with the time and and budget, it wasn't feasable.

Thanks again,
Chris
